# https://github.com/NiklasRosenstein/readthedocs-custom-steps/
steps:
  - git clone https://github.com/beliveau-lab/NUPACK.git
  - python3 -m pip install nupack -f NUPACK/src/package"
  - rm -r NUPACK"