
#!/bin/sh

# Python license
PY_VERSION=$(python3 -V)
# PY_PATH=$(python3 -c "import sys; print(min(sys.path[1:-1]))")
# PY_LICENSE=$(cd $PY_PATH && cat LICENSE*)

# Dependency licenses
python3 -m pip install pip-licenses
PIP_LICENSES=$(python3 -m piplicenses --with-system --from=mixed --format=markdown --with-urls)

read -r -d '' MAIN_TEXT << EOM
# Overview of third party libraries included within ToeholdTools

ToeholdTools is licensed under the terms of the [GPLv3](https://github.com/lkn849/thtools/blob/master/LICENSE).

However, the distributed app is made using [PyInstaller](https://github.com/pyinstaller/pyinstaller).
This means that it includes a standalone copy of $PY_VERSION and that all Python dependencies are bundled in as well.
The Python license is available [here](https://github.com/python/cpython/blob/main/LICENSE).

This is a compendium of projects which are packaged into the app,
generated by [pip-licenses](https://github.com/raimon49/pip-licenses) via our script [THIRD_PARTY_LICENSES.sh](https://github.com/lkn849/thtools/blob/master/THIRD_PARTY_LICENSES.sh).

To access this table from inside the app, click the button labelled \`Legal\` in the top right hand corner.

## Libraries included
$PIP_LICENSES
EOM

printf "$MAIN_TEXT" > THIRD_PARTY_LICENSES.md