name: Build
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build app
        run: src/thtools/app/build.sh

      - name: Install build requirements
        run: pip install setuptools wheel numpy Cython pygments pyinstaller

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
