name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
      CIBW_SKIP: pp* # Skip building for PyPy
      CIBW_BUILD_FRONTEND: "build" # build with https://github.com/pypa/build/ instead of pip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
