name: App
on:
  workflow_dispatch:  
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_wheels:
    name: Build app on ${{ matrix.os }} for ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest] # not windows because of NUPACK
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clone NUPACK
        run: git clone https://github.com/beliveau-lab/NUPACK.git

      - name: Install NUPACK
        run: pip install nupack -f NUPACK/src/package

      - name: Delete NUPACK repo
        run: rm -r NUPACK

      - name: Build app
        run: src/thtools/app/build.sh

      - name: Install build requirements
        run: pip install setuptools wheel numpy Cython pygments pyinstaller

      - name: Install ToeholdTools
        run: pip install -e .

      - name: Install UPX
        run: brew install upx

      - name: Run PyInstaller
        run: python3 -m thtools build ${{ matrix.os }}

      - name: Modify permissions
        run: chmod -R 777 ./apphouse/

      - uses: apple-actions/import-codesign-certs@v1
        if: ${{ matrix.os }} == 'macOS-latest'
        with: 
          p12-file-base64: ${{ secrets.CODESIGN_CERT }}
          p12-password: ${{ secrets.CODESIGN_CERT_PASS }}

      - uses: actions/upload-artifact@v2
        with:
          path: ./apphouse/*