name: Build
on: [workflow_dispatch, release]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
      CIBW_SKIP: pp*-macosx* # Skip building on PyPy on the Mac
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 # Used to host cibuildwheel

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0a4
        
      - name: Install build dependencies
        run: python -m pip install setuptools wheel numpy Cython --upgrade

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
#   deploy_wheels:
#     name: Deploy wheels to PyPI
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
      
